### PR TITLE
Fix pool memleak

### PR DESCRIPTION
**Pull request by nodech**
Address sanitizer of gcc and clang were able to catch `brontide malloc` not being freed. To reproduce with sanitizer you can run:
  - `make CFLAGS=-fsanitize=leak` or `make CFLAGS=-fsanitize=address`
  -  after you need to run `hnsd` for some time
  -  on close (e.g. `SIGINT`/C-c) you will see malloc that's not being freed.

```
=================================================================
==164637==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 9840 byte(s) in 6 object(s) allocated from:
    #0 0x7f7285449bc2 in __interceptor_malloc /build/gcc/src/gcc/libsanitizer/lsan/lsan_interceptors.cpp:56
    #1 0x55bbf9232270 in hsk_peer_init src/pool.c:804
    #2 0x55bbf9232270 in hsk_peer_alloc src/pool.c:877
    #3 0x55bbf9232270 in hsk_pool_refill src/pool.c:399

SUMMARY: LeakSanitizer: 9840 byte(s) leaked in 6 allocation(s).
```

### CODE REVIEW

**Comment by pinheadmz** [comment]
Great catch! Do we also need to add this here?

https://github.com/handshake-org/hnsd/blob/f599b071b7600ee9797651ec8c249ccac637e9b9/src/pool.c#L845-L849

**Comment by nodech** [comment]
For brontide `msg` that happens in `brontide_unininit` that is called by `hsk_peer_uninit`. https://github.com/handshake-org/hnsd/blob/f599b071b7600ee9797651ec8c249ccac637e9b9/src/brontide.c#L197-L206

**Comment by pinheadmz** [comment]
Or actually I wonder if your patch should go in this function, its similar to freeing the memory allocate for `peer->msg`:

https://github.com/handshake-org/hnsd/blob/master/src/pool.c#L854-L868

**Comment by nodech** [comment]
> Or actually I wonder if your patch should go in this function.

yeah, good catch. I like that better as well: `init` - allocs, `uninit` - frees.
I will move to uninit.

**Comment by nodech** [comment]
> its similar to freeing the memory allocate for peer->msg

Absolutely, if `peer->msg` allocation fails, we will leak brontide again !
Great catch, now it will free brontide if msg allocation fails.

**Comment by pinheadmz** [comment]
Mine as well link to https://github.com/handshake-org/hnsd/issues/45
I don't think this PR totally closes that issue though, will do some more testing

**Comment by nodech** [comment]
yeah, I don't think this rules out other leaks. Given the sizes I see on that log, there are some other leaks as well.

**Comment by pinheadmz** [comment]
Ok testing this was super easy, I detected memory leak after only like a minute of operation on master branch:

```
==68941==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 6560 byte(s) in 4 object(s) allocated from:
    #0 0x7f8025d4d5d1 in __interceptor_malloc ../../../../src/libsanitizer/lsan/lsan_interceptors.cpp:56
    #1 0x55fe910fa5b9 in hsk_peer_init src/pool.c:804
    #2 0x55fe910fa5b9 in hsk_peer_alloc src/pool.c:877
    #3 0x55fe910fa5b9 in hsk_pool_refill src/pool.c:399

SUMMARY: LeakSanitizer: 6560 byte(s) leaked in 4 allocation(s).

```

Testing on this branch, no such report

**Review by pinheadmz — APPROVED** [review]
ACK 9d0fd8dca7512c91fff4bdf0cdd90c79b307d167
<details><summary>Show Signature</summary>

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

ACK 9d0fd8dca7512c91fff4bdf0cdd90c79b307d167
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEE5hdzzW4BBA4vG9eM5+KYS2KJyToFAmFLUD4ACgkQ5+KYS2KJ
yTqsSg/8DzYT9Yl9VcyIAdw82nY8vzy9eHT5RHOuA/SRCJlWE3mDn8zGSD5ykbHi
fBM4vDKk9T8wK+C9J7noAuhoHdja3NEqCaFAgjGKOElph9iwebIUtzAtViPnnvYu
oEqopWXOmTe+J0VjnUryrLSyjo8rzUBT1P1nRCiTCmtzqo7B2SXFEE+j7sEp3vrJ
ZilAkTDVRLbFbWlUHC7Z2kDkD+/mWiaNWQXBUkk8279avPdV3VwPvB+rh8frQoKa
+CrGmGbBGOwr4pJbWVoCpgeomZfqbIkih2qxgB7MktTtfDj1Sc7sS5rFdesqGUxn
lgaJCSQPqA3GVy+xtd/HzkV/kJJed1DEAK0CcxuABJKBwWpeQTyM0937cTDzkldA
zkXQfx/H54NQskf2lsn4QlfurVgXImRzf+l47PpOpTCwzWaLDcCE45nEGTlFUQny
0YlVMCNMDn9DKLksgjGTwkBWuJPbWjR5GBIhI1AY6eQ53/mWk1mfV4pVno+d0nAi
7v5Kw80yfjFgUFv/9nsiq2+xZ/vi7xh9cHIfRWj6sWtzoBAgMTCIeFZk4ysebgED
uVXwfIrJSxWUMGl1Fr26t8qXx02d2MVacpQIN5GGg45+E0qQ9C0U16ZEPloZc54H
jA1KW0ZuoQuvTgc63G8nMjBn2XdFPiafrP2S2liyf8EJUfM71V4=
=qxPX
-----END PGP SIGNATURE-----
```

pinheadmz's public key is [on keybase](https://keybase.io/pinheadmz/pgp_keys.asc?fingerprint=e61773cd6e01040e2f1bd78ce7e2984b6289c93a)
</details>

**Pull request merged**
