### PR TITLE
add Dockerfile and Readme (update)

### PR DESCRIPTION
**Pull request by pinheadmz**
Replaces https://github.com/handshake-org/hnsd/pull/50

### CODE REVIEW

**Comment by pinheadmz** [comment]
Tested successfully...

✅  OSX 10.14.6
✅  Ubuntu 20.04.1

**Comment by pinheadmz** [comment]
Ok finally got this to work in Docker on Windows also, trick was configuring git to leave the end-of-line characters alone so that they wouldn't crash inside of the Alpine container 🙄:

```
$ git config --global core.autocrlf input
```
 Besides that the only issue was something to do with the git version pinned in the Dockerfile so Im just going to take those version pins out and test again on all 3 systems

**Comment by rithvikvibhu** [comment]
Couldn't build on `Manjaro release 20.2.1`:

```
❯ sudo docker build -t hnsd .
Sending build context to Docker daemon  18.46MB
Step 1/10 : FROM alpine:3 AS base
3: Pulling from library/alpine
ba3557a56b15: Pull complete 
Digest: sha256:a75afd8b57e7f34e4dad8d65e2c7ba2e1975c795ce1ee22fa34f8cf46f96a3be
Status: Downloaded newer image for alpine:3
 ---> 28f6e2705743
Step 2/10 : COPY . /
 ---> 56e91b010432
Step 3/10 : FROM base AS build
 ---> 56e91b010432
Step 4/10 : RUN apk add --no-cache   build-base=0.5-r2   git=2.30.1-r0   automake=1.16.3-r0   autoconf=2.69-r3   libtool=2.4.6-r7   unbound-dev=1.13.0-r3
 ---> Running in 7888355844c4
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
ERROR: unable to select packages:
  git-2.30.2-r0:
    breaks: world[git=2.30.1-r0]
The command '/bin/sh -c apk add --no-cache   build-base=0.5-r2   git=2.30.1-r0   automake=1.16.3-r0   autoconf=2.69-r3   libtool=2.4.6-r7   unbound-dev=1.13.0-r3' returned a non-zero code: 1
```

**Comment by pinheadmz** [comment]
@rithvikvibhu I updated the dockerfile and readme and tested again on OSX, Ubuntu and Windows without failure.

Can you give the PR one more look over and give me an ACK if its good? I think we can merge.

**Comment by rithvikvibhu** [comment]
Cool, works without any changes now.

**Pull request merged**
